/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/views/AboutView.vue')['default']
    App: typeof import('./src/App.vue')['default']
    DefaultLayout: typeof import('./src/layout/DefaultLayout.vue')['default']
    HomeView: typeof import('./src/views/HomeView/HomeView.vue')['default']
    IconPhUploadSimple: typeof import('~icons/ph/upload-simple')['default']
    LoadSpinner: typeof import('./src/components/LoadSpinner.vue')['default']
    NoResults: typeof import('./src/views/HomeView/components/NoResults.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PostCard: typeof import('./src/views/HomeView/components/PostCard.vue')['default']
    PostData: typeof import('./src/views/PostDetailsView/components/PostData.vue')['default']
    PostDetailsView: typeof import('./src/views/PostDetailsView/PostDetailsView.vue')['default']
    PostList: typeof import('./src/views/HomeView/components/PostList.vue')['default']
    PostMarkdownViewer: typeof import('./src/components/PostMarkdownViewer.vue')['default']
    Profile: typeof import('./src/views/HomeView/components/Profile.vue')['default']
    ProfileCard: typeof import('./src/views/HomeView/components/ProfileCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
  }
}
